<?php

return [
    'projects' => [
        'title' => 'Projects',
        'table' => 'projects',
        'permission' => 'projects',
        'order' => 'deadline ASC',
        'search' => ['project_name', 'category', 'description', 'priority', 'status', 'source'],
        'fields' => [
            'project_name' => ['label' => 'Project Name', 'type' => 'text', 'required' => true],
            'category' => ['label' => 'Category', 'type' => 'select', 'options' => ['In House', 'Another'], 'required' => true],
            'description' => ['label' => 'Description', 'type' => 'textarea'],
            'source' => ['label' => 'Source', 'type' => 'select', 'options' => ['Direct', 'Upwork', 'Fiverr', 'WhatsApp', 'Other'], 'required' => true],
            'priority' => ['label' => 'Priority', 'type' => 'select', 'options' => ['High', 'Medium', 'Low'], 'required' => true],
            'start_date' => ['label' => 'Start Date', 'type' => 'date', 'required' => true],
            'deadline' => ['label' => 'Deadline', 'type' => 'date', 'required' => true],
            'assigned_to' => ['label' => 'Assigned To', 'type' => 'virtual', 'list' => false],
            'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['Not Started', 'Pending', 'In Progress', 'In Review', 'On Hold', 'Waiting on Client', 'Revision', 'Completed', 'Delivered', 'Finished'], 'required' => true],
            'progress' => ['label' => 'Progress', 'type' => 'number', 'required' => true, 'min' => 0, 'max' => 100],
            'notes' => ['label' => 'Notes', 'type' => 'textarea'],
        ],
    ],
    'employees' => [
        'title' => 'Employees',
        'table' => 'employees',
        'permission' => 'employees',
        'order' => 'name ASC',
        'search' => ['employee_code', 'name', 'department', 'designation', 'email', 'phone'],
        'fields' => [
            'employee_code' => ['label' => 'Employee ID', 'type' => 'text', 'required' => true],
            'name' => ['label' => 'Name', 'type' => 'text', 'required' => true],
            'department' => ['label' => 'Department', 'type' => 'department_select', 'required' => true],
            'designation' => ['label' => 'Designation', 'type' => 'text', 'required' => true],
            'phone' => ['label' => 'Phone', 'type' => 'text'],
            'email' => ['label' => 'Email', 'type' => 'email', 'required' => true],
            'joining_date' => ['label' => 'Joining Date', 'type' => 'date', 'required' => true],
            'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['Active', 'Inactive'], 'required' => true],
            'emergency_contact' => ['label' => 'Emergency Contact', 'type' => 'text'],
        ],
    ],
    'departments' => [
        'title' => 'Departments',
        'table' => 'departments',
        'permission' => 'departments',
        'order' => 'department_name ASC',
        'search' => ['department_name', 'manager', 'status'],
        'fields' => [
            'department_name' => ['label' => 'Department Name', 'type' => 'text', 'required' => true],
            'manager' => ['label' => 'Manager', 'type' => 'text'],
            'description' => ['label' => 'Description', 'type' => 'textarea'],
            'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['Active', 'Inactive'], 'required' => true],
        ],
    ],
    'requirements' => [
        'title' => 'Requirements',
        'table' => 'requirements',
        'permission' => 'requirements',
        'order' => 'required_date ASC',
        'search' => ['item', 'vendor', 'status', 'priority'],
        'fields' => [
            'item' => ['label' => 'Item', 'type' => 'text', 'required' => true],
            'quantity' => ['label' => 'Quantity', 'type' => 'number', 'required' => true],
            'priority' => ['label' => 'Priority', 'type' => 'select', 'options' => ['High', 'Medium', 'Low'], 'required' => true],
            'required_date' => ['label' => 'Required Date', 'type' => 'date', 'required' => true],
            'vendor' => ['label' => 'Vendor', 'type' => 'text'],
            'estimated_cost' => ['label' => 'Estimated Cost', 'type' => 'number'],
            'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['Pending', 'Ordered', 'Purchased', 'Received'], 'required' => true],
            'remarks' => ['label' => 'Remarks', 'type' => 'textarea'],
        ],
    ],
    'pending-tasks' => [
        'title' => 'Pending Tasks',
        'table' => 'pending_tasks',
        'permission' => 'pending_tasks',
        'order' => 'required_date ASC, created_at DESC',
        'search' => ['task_title', 'category', 'assigned_to', 'status', 'priority'],
        'fields' => [
            'task_title' => ['label' => 'Task', 'type' => 'text', 'required' => true],
            'category' => ['label' => 'Category', 'type' => 'text'],
            'priority' => ['label' => 'Priority', 'type' => 'select', 'options' => ['High', 'Medium', 'Low'], 'required' => true],
            'required_date' => ['label' => 'Required Date', 'type' => 'date'],
            'assigned_to' => ['label' => 'Assigned To', 'type' => 'virtual', 'list' => true],
            'status' => ['label' => 'Status', 'type' => 'select', 'options' => ['Pending', 'In Progress', 'Completed'], 'required' => true],
            'remarks' => ['label' => 'Remarks', 'type' => 'textarea'],
        ],
    ],
    'employee-fines' => [
        'title' => 'Employee Fines',
        'table' => 'employee_fines',
        'permission' => 'fines',
        'order' => 'fine_date DESC',
        'search' => ['employee_name', 'reason', 'approved_by', 'paid'],
        'fields' => [
            'employee_name' => ['label' => 'Employee', 'type' => 'text', 'required' => true],
            'reason' => ['label' => 'Reason', 'type' => 'textarea', 'required' => true],
            'amount' => ['label' => 'Amount', 'type' => 'number', 'required' => true],
            'fine_date' => ['label' => 'Date', 'type' => 'date', 'required' => true],
            'paid' => ['label' => 'Paid', 'type' => 'select', 'options' => ['No', 'Yes'], 'required' => true],
            'approved_by' => ['label' => 'Approved By', 'type' => 'text'],
            'remarks' => ['label' => 'Remarks', 'type' => 'textarea'],
        ],
    ],
    'documents' => [
        'title' => 'Documents',
        'table' => 'documents',
        'permission' => 'documents',
        'order' => 'created_at DESC',
        'search' => ['title', 'category', 'version'],
        'fields' => [
            'title' => ['label' => 'Title', 'type' => 'text', 'required' => true],
            'category' => ['label' => 'Category', 'type' => 'text', 'required' => true],
            'version' => ['label' => 'Version', 'type' => 'text', 'required' => true],
            'description' => ['label' => 'Description', 'type' => 'textarea'],
            'file_path' => ['label' => 'Attachment', 'type' => 'file'],
        ],
    ],
    'announcements' => [
        'title' => 'Announcements',
        'table' => 'announcements',
        'permission' => 'announcements',
        'order' => 'start_date DESC, created_at DESC',
        'search' => ['title', 'type', 'content'],
        'fields' => [
            'title' => ['label' => 'Title', 'type' => 'text', 'required' => true],
            'type' => ['label' => 'Type', 'type' => 'select', 'options' => ['General', 'Important', 'Urgent', 'Update'], 'required' => true],
            'start_date' => ['label' => 'Start Date', 'type' => 'date', 'required' => true],
            'end_date' => ['label' => 'End Date (Auto-Expiry)', 'type' => 'date', 'required' => true],
            'content' => ['label' => 'Content', 'type' => 'textarea', 'required' => true],
        ],
    ],
    'users' => [
        'title' => 'Users',
        'table' => 'users',
        'permission' => 'users',
        'admin_only' => true,
        'order' => 'name ASC',
        'search' => ['name', 'email', 'status'],
        'fields' => [
            'name'     => ['label' => 'Name',   'type' => 'text',     'required' => true],
            'email'    => ['label' => 'Email',  'type' => 'email',    'required' => true],
            'password' => ['label' => 'Password','type' => 'password', 'list' => false],
            'role_id'  => ['label' => 'Role',   'type' => 'roles_select', 'required' => true, 'list' => false],
            'role_name'=> ['label' => 'Role',   'type' => 'virtual',  'list' => true],
            'status'   => ['label' => 'Status', 'type' => 'select',   'options' => ['Active', 'Inactive'], 'required' => true],
        ],
    ],
    'roles' => [
        'title' => 'Roles',
        'table' => 'roles',
        'permission' => 'roles',
        'admin_only' => true,
        'order' => 'name ASC',
        'search' => ['name', 'description'],
        'fields' => [
            'name' => ['label' => 'Role Name', 'type' => 'text', 'required' => true],
            'description' => ['label' => 'Description', 'type' => 'textarea'],
        ],
    ],
    'permissions' => [
        'title' => 'Permissions',
        'table' => 'permissions',
        'permission' => 'permissions',
        'admin_only' => true,
        'order' => 'module ASC',
        'search' => ['module', 'action'],
        'fields' => [
            'module' => ['label' => 'Module', 'type' => 'text', 'required' => true],
            'action' => ['label' => 'Action', 'type' => 'text', 'required' => true],
        ],
    ],
];
